### ISSUE TITLE
Can you add module for purchase content 

### ISSUE THREAD

**Issue by smallworl** [Avnsx/fansly#12] opened 2022-02-10 23:20 UTC
i would like to download my purchase content if possible the url is below thank you
https://fansly.com/collection

thanks in advanced

**Comment by blunderedbishop** [comment] 2022-10-11 20:00
Wouldn't it be enough to make a log-in request and the run the script with the acquired cookies? Sorry but i don't have any paid content to test this with.

**Comment by Avnsx** [comment] 2022-10-13 17:40
No my code does not support purchased (``/collection``) content. The reason it doesn't is, because I'm not planning to pay for porn ever, so I can't ever add this 🤷‍♂️

If anyone really wants fansly scraper to have purchased content supported; send fansly account credentials with username & password with access to any purchased content to ``AvnDev[at]pm.me``

**Comment by Litvan** [comment] 2022-10-20 00:52
What about pictures in private messages?

**Comment by Avnsx** [comment] 2022-10-21 07:54
> What about pictures in private messages?

Already supported

**Comment by Litvan** [comment] 2022-10-21 21:53
> > What about pictures in private messages?
> 
> Already supported

well last I used it, it didn't scrape anything from the specific creator that I had in my DM's from that person

**Comment by Nostang3** [comment] 2022-12-11 21:55
I can confirm it still doesn't scrap my purchase content from my DM's.

**Comment by Photofreak** [comment] 2023-01-27 16:22
I am unable to load purchases content from Fansly in the DM/Chat.

**Comment by Avnsx** [comment] 2023-05-08 18:52
Hey thanks to one of you guys DM'ing me a fansly account I could add the support for collections & single posts.

After you download the new fansly_scraper.py & config.ini files manually, you'll be able to configure a download_mode option in config.ini. This option allows you to set it to:
"Single "-> if you set it on single, once you launch the scraper it will ask you what post by id, you want to download
"Collection" -> adds support for collections, you launch the scraper it just downloads everything you ever paid for

None of these options support hashing or update_recent_download at the moment. I am planning to add that in a whole re-write of fansly scraper, later on.

You can currently only use it in the python version: https://github.com/Avnsx/fansly/commit/b30a65df220f13b95cba5fa4e5b032baa82a1d75

If anyone knows how to [set the python version up](https://github.com/Avnsx/fansly#%EF%B8%8F-set-up) properly, let me know if you think that these options are a good implementation or not.

Will release a compiled release later this week

**Comment by Avnsx** [comment] 2023-06-12 12:26
Closing, as the [0.4 version is finally released](https://github.com/Avnsx/fansly-downloader/releases/tag/v0.4) and does target & solve the topics mentioned within this issue.

**Closed as completed by Avnsx** 2023-06-12 12:26 UTC
Labels: added feature
