### ISSUE TITLE
Help: Does not scrape photos from messages

### ISSUE THREAD

**Issue by Photofreak** [Avnsx/fansly#65] opened 2023-01-20 20:54 UTC
The scaper does not pull/scrape photos from the messages I have purchased.  The app does a good job scraping from the home page but fails to get the photos from the message or chat stream.

**Comment by Avnsx** [comment] 2023-01-21 09:59
duplicate of: https://github.com/Avnsx/fansly/issues/12

**Closed by Avnsx** 2023-01-21 09:59 UTC
