### ISSUE TITLE
No Inbox Media

### ISSUE THREAD

**Issue by raucodes** [Avnsx/fansly#60] opened 2022-12-15 16:50 UTC
Hi, I have 4 Photos in inbox and it is in with my subscription and can see the Photo, but in Messages Folder is nothing... I also recreated the Dir but the error keeps persist.

**Comment by Avnsx** [comment] 2022-12-15 17:03
duplicate of: https://github.com/Avnsx/fansly/issues/59

**Closed by Avnsx** 2022-12-15 17:03 UTC
